# Generated by Django 4.1.7 on 2023-03-29 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location_id', models.IntegerField()),
                ('drone_shot_id', models.IntegerField()),
                ('datetime', models.DateTimeField(default=datetime.datetime(2023, 3, 29, 3, 43, 45, 476469, tzinfo=datetime.timezone.utc))),
                ('totalRent', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('addedBy', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('mobileNo', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('aadhaarNo', models.CharField(max_length=12)),
                ('addedBy', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DroneShot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
                ('addedBy', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'drone_shot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('addedBy', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=30)),
                ('access', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'operator',
                'managed': False,
            },
        ),
    ]
